apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "howlseve.fullname" . }}
  labels:
    app: {{ template "howlseve.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: {{ template "howlseve.fullname" . }}
    app.kubernetes.io/version: "{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "howlseve.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "howlseve.fullname" . }}
    spec:
      containers:
        - name: {{ template "howlseve.fullname" . }}
          image: {{ .Values.image }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: web
              containerPort: 8000